#!/usr/bin/env python3
"""
Resort To Grow — Configuration Server
Runs on port 1423, serves the web-based config UI
"""

import http.server
import socketserver
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse
import webbrowser

PORT = 1423
DIRECTORY = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = Path(DIRECTORY).parent
CONFIG_FILE = PROJECT_ROOT / 'app' / 'src' / 'config.js'
IMAGES_DIR = PROJECT_ROOT / 'app' / 'src' / 'images'


class ConfigParser:
    """Parse config.js into JSON and back"""
    
    @staticmethod
    def parse_js_to_dict(content):
        config = {}
        
        match = re.search(r'timerIntervalMinutes:\s*(\d+)', content)
        config['timerIntervalMinutes'] = int(match.group(1)) if match else 30
        
        match = re.search(r"dashboardUrl:\s*'((?:[^'\\]|\\.)*)'", content)
        config['dashboardUrl'] = match.group(1).replace("\\'", "'").replace("\\\\", "\\") if match else 'http://localhost:1422'
        
        config['images'] = {}
        for key in ['mainPhoto', 'pleaImage', 'motivationLeft', 'motivationRight', 'summaryLeft', 'summaryRight']:
            match = re.search(rf"{key}:\s*'((?:[^'\\]|\\.)*)'", content)
            config['images'][key] = match.group(1).replace("\\'", "'").replace("\\\\", "\\") if match else '/placeholder.jpg'
        
        config['checkin'] = {}
        for key in ['question', 'yesButton', 'noButton', 'summaryLink']:
            match = re.search(rf"{key}:\s*'((?:[^'\\]|\\.)*)'", content)
            config['checkin'][key] = match.group(1).replace("\\'", "'").replace("\\\\", "\\") if match else ''
        
        config['noPath'] = {}
        for key in ['pleaQuestion', 'pleaButton', 'worthyButton']:
            match = re.search(rf"{key}:\s*'((?:[^'\\]|\\.)*)'", content)
            config['noPath'][key] = match.group(1).replace("\\'", "'").replace("\\\\", "\\") if match else ''
        
        config['journey'] = []
        journey_pattern = r"question:\s*'((?:[^'\\]|\\.)*)'.*?button:\s*'((?:[^'\\]|\\.)*)'.*?image:\s*'((?:[^'\\]|\\.)*)'"
        for match in re.finditer(journey_pattern, content, re.DOTALL):
            config['journey'].append({
                'question': match.group(1).replace("\\'", "'").replace("\\\\", "\\"),
                'button': match.group(2).replace("\\'", "'").replace("\\\\", "\\"),
                'image': match.group(3).replace("\\'", "'").replace("\\\\", "\\")
            })
        
        config['quotes'] = {}
        for key in ['trigger', 'yesHeadline', 'yesSub', 'encouragement', 'customAdvice']:
            pattern = rf"{key}:\s*\[(.*?)\]"
            match = re.search(pattern, content, re.DOTALL)
            if match:
                raw = match.group(1)
                quotes = re.findall(r"'((?:[^'\\]|\\.)*)'", raw)
                config['quotes'][key] = [q.replace("\\'", "'").replace("\\\\", "\\") for q in quotes]
            else:
                config['quotes'][key] = []
        
        config['problems'] = []
        problem_pattern = r"id:\s*'((?:[^'\\]|\\.)*)'.*?label:\s*'((?:[^'\\]|\\.)*)'.*?advice:\s*'((?:[^'\\]|\\.)*)'"
        for match in re.finditer(problem_pattern, content, re.DOTALL):
            config['problems'].append({
                'id': match.group(1).replace("\\'", "'").replace("\\\\", "\\"),
                'label': match.group(2).replace("\\'", "'").replace("\\\\", "\\"),
                'advice': match.group(3).replace("\\'", "'").replace("\\\\", "\\")
            })
        
        config['window'] = {
            'default': {'width': 600, 'height': 680},
            'dualImages': {'width': 1040, 'height': 760}
        }
        
        return config
    
    @staticmethod
    def generate_js_from_dict(config):
        def escape_js(s):
            return s.replace("\\", "\\\\").replace("'", "\\'")
        
        js = f"""// ================================================================
//  CONFIG.JS — All your personal customizations live here.
//  You do NOT need to touch any other file to change the content.
//
//  Generated by Config UI at http://localhost:{PORT}
// ================================================================

export const CONFIG = {{

  // Timer (in minutes)
  timerIntervalMinutes: {config['timerIntervalMinutes']},

  // Dashboard URL
  dashboardUrl: '{escape_js(config['dashboardUrl'])}',

  // Images
  images: {{
    mainPhoto: '{escape_js(config['images']['mainPhoto'])}',
    pleaImage: '{escape_js(config['images']['pleaImage'])}',
    motivationLeft: '{escape_js(config['images']['motivationLeft'])}',
    motivationRight: '{escape_js(config['images']['motivationRight'])}',
    summaryLeft: '{escape_js(config['images']['summaryLeft'])}',
    summaryRight: '{escape_js(config['images']['summaryRight'])}',
  }},

  // Check-in page
  checkin: {{
    question: '{escape_js(config['checkin']['question'])}',
    yesButton: '{escape_js(config['checkin']['yesButton'])}',
    noButton: '{escape_js(config['checkin']['noButton'])}',
    summaryLink: '{escape_js(config['checkin']['summaryLink'])}',
  }},

  // "Not really" flow
  noPath: {{
    pleaQuestion: '{escape_js(config['noPath']['pleaQuestion'])}',
    pleaButton: '{escape_js(config['noPath']['pleaButton'])}',
    worthyButton: '{escape_js(config['noPath']['worthyButton'])}',
  }},

  // Journey (affirmation screens)
  journey: [
"""
        for step in config.get('journey', []):
            js += f"""    {{
      question: '{escape_js(step['question'])}',
      button: '{escape_js(step['button'])}',
      image: '{escape_js(step['image'])}',
    }},
"""
        js += """  ],

  // Motivational quotes
  quotes: {
"""
        for key in ['trigger', 'yesHeadline', 'yesSub', 'encouragement', 'customAdvice']:
            js += f"    {key}: [\n"
            for quote in config.get('quotes', {}).get(key, []):
                js += f"      '{escape_js(quote)}',\n"
            js += "    ],\n"
        
        js += """  },

  // Problem picker
  problems: [
"""
        for problem in config.get('problems', []):
            js += f"""    {{
      id: '{escape_js(problem['id'])}',
      label: '{escape_js(problem['label'])}',
      advice: '{escape_js(problem['advice'])}',
    }},
"""
        js += f"""  ],

  // Window sizes
  window: {{
    default: {{ width: {config['window']['default']['width']}, height: {config['window']['default']['height']} }},
    dualImages: {{ width: {config['window']['dualImages']['width']}, height: {config['window']['dualImages']['height']} }},
  }},

}};
"""
        return js


class ConfigHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)
    
    def do_GET(self):
        parsed = urlparse(self.path)
        
        if parsed.path == '/api/config':
            self.handle_get_config()
        elif parsed.path == '/api/images':
            self.handle_get_images()
        elif parsed.path.startswith('/images/'):
            self.handle_serve_image(parsed.path)
        else:
            super().do_GET()
    
    def do_POST(self):
        parsed = urlparse(self.path)
        
        if parsed.path == '/api/config':
            self.handle_post_config()
        elif parsed.path == '/api/images':
            self.handle_post_image()
        else:
            self.send_error(404)
    
    def do_DELETE(self):
        parsed = urlparse(self.path)
        
        if parsed.path.startswith('/api/images/'):
            name = parsed.path.split('/')[-1]
            self.handle_delete_image(name)
        else:
            self.send_error(404)
    
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
    
    def handle_get_config(self):
        if CONFIG_FILE.exists():
            content = CONFIG_FILE.read_text()
            config = ConfigParser.parse_js_to_dict(content)
        else:
            config = self.get_default_config()
        
        self.send_json(config)
    
    def handle_post_config(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        config = json.loads(body)
        
        js_content = ConfigParser.generate_js_from_dict(config)
        CONFIG_FILE.write_text(js_content)
        
        self.send_json({'success': True})
    
    def handle_get_images(self):
        images = []
        if IMAGES_DIR.exists():
            for f in IMAGES_DIR.iterdir():
                if f.suffix.lower() in ['.jpg', '.jpeg', '.png', '.webp']:
                    images.append({
                        'name': f.name,
                        'size': f.stat().st_size,
                        'url': f'/images/{f.name}'
                    })
        self.send_json(images)
    
    def handle_serve_image(self, path):
        filename = path.split('/')[-1]
        file_path = IMAGES_DIR / filename
        
        if file_path.exists():
            self.send_response(200)
            ext = file_path.suffix.lower()
            content_types = {
                '.jpg': 'image/jpeg',
                '.jpeg': 'image/jpeg',
                '.png': 'image/png',
                '.webp': 'image/webp'
            }
            self.send_header('Content-type', content_types.get(ext, 'application/octet-stream'))
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(file_path.read_bytes())
        else:
            self.send_error(404)
    
    def handle_post_image(self):
        content_type = self.headers.get('Content-Type', '')
        if 'multipart/form-data' not in content_type:
            self.send_json({'error': 'Invalid content type'}, 400)
            return
        
        boundary = content_type.split('boundary=')[1].encode()
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        
        parts = body.split(boundary)
        for part in parts:
            if b'filename="' in part:
                filename_match = re.search(b'filename="([^"]+)"', part)
                if filename_match:
                    filename = filename_match.group(1).decode()
                    file_data = part.split(b'\r\n\r\n', 1)[1]
                    file_data = file_data.rsplit(b'\r\n', 1)[0]
                    
                    file_path = IMAGES_DIR / filename
                    file_path.write_bytes(file_data)
                    
                    self.send_json({'success': True, 'filename': filename})
                    return
        
        self.send_json({'error': 'No file found'}, 400)
    
    def handle_delete_image(self, name):
        file_path = IMAGES_DIR / name
        if file_path.exists():
            file_path.unlink()
            self.send_json({'success': True})
        else:
            self.send_json({'error': 'File not found'}, 404)
    
    def send_json(self, data, status=200):
        self.send_response(status)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(json.dumps(data).encode('utf-8'))
    
    def get_default_config(self):
        return {
            'timerIntervalMinutes': 30,
            'dashboardUrl': 'http://localhost:1422',
            'images': {k: '/placeholder.jpg' for k in ['mainPhoto', 'pleaImage', 'motivationLeft', 'motivationRight', 'summaryLeft', 'summaryRight']},
            'checkin': {
                'question': 'Are you really working hard right now?',
                'yesButton': 'Yes, I am',
                'noButton': 'Not really',
                'summaryLink': "Today's progress"
            },
            'noPath': {
                'pleaQuestion': "[Name], don't you want to achieve your goals?",
                'pleaButton': 'I will work hard',
                'worthyButton': 'I have to become worthy'
            },
            'journey': [
                {'question': 'I am becoming the best version of myself.', 'button': 'Yes, I am.', 'image': '/placeholder.jpg'},
                {'question': 'Every minute of focus brings me closer to my goals.', 'button': 'Absolutely.', 'image': '/placeholder.jpg'},
                {'question': 'I will not waste this opportunity.', 'button': 'Never.', 'image': '/placeholder.jpg'}
            ],
            'quotes': {
                'trigger': ['Your future self is watching you right now.', 'Every wasted minute is a choice you made.'],
                'yesHeadline': ['Good. Keep going.', "Respect. Don't stop now."],
                'yesSub': ["You're building something real. Don't stop now.", 'Consistency separates winners from everyone else.'],
                'encouragement': ["You're smarter than this. Find a way to adapt.", 'One small step right now changes everything.'],
                'customAdvice': ['Take a deep breath. Write down what is really wrong.', 'Break it down. What is the ONE thing you can do in the next 5 minutes?']
            },
            'problems': [
                {'id': 'distraction', 'label': 'Distraction', 'advice': 'Close the distraction right now.'},
                {'id': 'laziness', 'label': 'Laziness', 'advice': "Just start for 5 minutes."},
                {'id': 'confusion', 'label': 'Confusion', 'advice': 'Break it into 3 tiny steps.'},
                {'id': 'low-energy', 'label': 'Low Energy', 'advice': 'Stand up. Drink water.'}
            ],
            'window': {
                'default': {'width': 600, 'height': 680},
                'dualImages': {'width': 1040, 'height': 760}
            }
        }
    
    def log_message(self, format, *args):
        print(f"[Config UI] {args[0]}")


def is_port_in_use(port):
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('localhost', port)) == 0


def main(open_browser=True):
    if is_port_in_use(PORT):
        print(f"Config server already running on port {PORT}")
        if open_browser:
            webbrowser.open(f"http://localhost:{PORT}")
        sys.exit(0)
    
    os.chdir(DIRECTORY)
    socketserver.TCPServer.allow_reuse_address = True
    
    print(f"Starting config server at http://localhost:{PORT}")
    print(f"Config file: {CONFIG_FILE}")
    print(f"Images directory: {IMAGES_DIR}")
    
    if open_browser:
        webbrowser.open(f"http://localhost:{PORT}")
    
    with socketserver.TCPServer(("", PORT), ConfigHandler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down config server.")


if __name__ == '__main__':
    main()
